### ISSUE TITLE
use reflect-metadata?

### ISSUE THREAD

**Issue by amcdnl** [mvila/event-emitter-mixin#2]
you should use [reflect-metadata](https://www.npmjs.com/package/reflect-metadata) for adding prototype hooks on your decorators

**Comment by mvila** [comment]
Thanks @amcdnl but I am not sure to understand how to use these metadata. Could you expand a little?

**Comment by amcdnl** [comment]
Rather than attaching to the prototype, you register it as meta-data.  See this for an example: https://github.com/pleerock/controllers.ts/blob/master/src/Decorators.ts#L278

**Comment by mvila** [comment]
Oh yes, it would be a quite elegant solution. I'll consider it. Thanks for your feedback.

**Comment by amcdnl** [comment]
np :)
